version: '2'

services:
    reverseproxy:
        image: keithtanhere/nginx-reverseproxy
        ports:
            - 8080:8080
        restart: always

    http:
        depends_on:
            - reverseproxy
        image: keithtanhere/nginx-http
        restart: always
